### ISSUE TITLE
React Router

### ISSUE THREAD

**Issue by omarbelkady** [omarbelkady/React#18]

**Comment by rahulbhatt1899** [comment]
Hey, could you provide some information about the issue?

**Comment by omarbelkady** [comment]
This is just for me to incorporate in my repo.

**Comment by rahulbhatt1899** [comment]
Ohh thank you for following :)

**Comment by omarbelkady** [comment]
If there is anything you can share for me to advance my knowledge in React. I would highly appreciate it! Feel free to review my code and tell me anything I need to improve. Thank you so much.
